# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d19d9ec5ce0f287054842c0f41adba2a5afaef53440dfcc23941345ffb303cb450ba2e7da76d28095760e541733687ebe75b45d1e5ac3035b5e0de2f92934204

test:
  secret_key_base: 2a34dd40a88b3f18a21f153a54ebe65bba079db4ae4764b822930884c36147b99bd634a629947437efcbacfbc924178c5cffe381fb24a183e001345fd5b5cf48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
